#!/usr/bin/env zsh -e
#
# FFmpeg
# https://git.ffmpeg.org/ffmpeg.git
#

set -e

PS4='+ ${BASH_SOURCE}:${LINENO}: '

error_report() {
    echo "Error on line $1"
}

trap 'error_report $LINENO' ERR

cd "$(dirname "$0")"
set -a; source build.env; set +a
source utils/pkg-import

pkgname="ffmpeg"
pkgdir="$1"
srcdir="src/ffmpeg"

import_local_pkg $pkgdir

cd "${srcdir}"

./configure \
  --prefix="${pkgdir}" \
  --pkg-config="${PKG_CONFIG}" \
  --arch="$(arch)" \
  --cpu=host \
  --cc=clang \
  --enable-shared \
  --enable-ffplay \
  --enable-lto \
  --enable-gpl \
  --enable-version3 \
  --enable-nonfree \
  --enable-lcms2 \
  --enable-libass \
  --enable-libdav1d \
  --enable-libfreetype \
  --enable-libfribidi \
  --enable-libharfbuzz \
  --enable-libjxl \
  --enable-libmp3lame \
  --enable-libopus \
  --enable-libplacebo \
  --enable-libshaderc \
  --enable-libsvtav1 \
  --enable-libvorbis \
  --enable-libvpx \
  --enable-libwebp \
  --enable-libx264 \
  --enable-libx265 \
  --enable-libxml2 \
  --enable-libzimg \
  --enable-openssl \
  --disable-static \
  --disable-debug \
  --disable-doc \
  --disable-sdl2 \
  --disable-libxcb \
  --disable-xlib \
  # "$@"

make -j$(sysctl -n hw.physicalcpu)

# rm -rf "${pkgdir}"

make install
# rm -rf "${pkgdir}"/share

# vi:set ts=2 sw=2 et:
