#!/bin/bash -e
#
# Mesa
# https://gitlab.freedesktop.org/mesa/mesa.git
#
# Homebrew dependencies:
# libclc spirv-llvm-translator
#
cd "$(dirname "$0")"
set -a; . .env; set +a

pkgname="mesa"
pkgdir="${STOWDIR}/${pkgname}"
srcdir="src/mesa"
builddir="${TMPDIR:-/tmp}/build.${pkgname}"

echo "::group::$0"

rm -rf "${builddir}"

meson setup "${builddir}" "${srcdir}" \
  --prefix="${pkgdir}" \
  --native-file=meson/native/llvm.ini \
  -Dwrap_mode=nodownload \
  -Dbuildtype=release \
  -Dplatforms=macos \
  -Dvulkan-drivers=kosmickrisp \
  -Dvulkan-icd-dir="${pkgdir}/etc/vulkan/icd.d" \
  -Dgallium-drivers=[] \
  -Dvideo-codecs=all \
  -Dopengl=false \
  -Dgles1=disabled \
  -Dgles2=disabled \
  -Dglx=disabled \
  -Dxmlconfig=disabled \
  -Dzstd=disabled \
  "$@"

meson compile -C "${builddir}"

rm -rf "${pkgdir}"

meson install -C "${builddir}"
stow -Rd "${STOWDIR}" "${pkgname}"

rm -rf "${builddir}"

echo "::endgroup::"
