#!/usr/bin/env bash -e
#
# brotli
# https://github.com/google/brotli.git
#
cd "$(dirname "$0")"
set -a; . .env; set +a

pkgname="brotli"
pkgdir="${STOWDIR}/${pkgname}"
srcdir="src/brotli"
builddir="${TMPDIR:-/tmp}/build.${pkgname}"

rm -rf "${builddir}"

cmake -B "${builddir}" -S "${srcdir}" \
  -DCMAKE_INSTALL_PREFIX="${pkgdir}" \
  -DCMAKE_INSTALL_NAME_DIR="${pkgdir}/lib" \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON \
  -DBROTLI_DISABLE_TESTS=ON \
  -DBROTLI_BUILD_TOOLS=OFF \
  "$@"

cmake --build "${builddir}"

rm -rf "${pkgdir}"

cmake --install "${builddir}"
rm -rf "${pkgdir}"/share
stow -Rd "${STOWDIR}" "${pkgname}"

rm -rf "${builddir}"
