#!/usr/bin/env bash -e
#
# HarfBuzz
# https://github.com/harfbuzz/harfbuzz.git
#
cd "$(dirname "$0")"
set -a; source build.env; set +a

pkgname="harfbuzz"
pkgdir="${STOWDIR}/${pkgname}"
srcdir="src/harfbuzz"
builddir="${TMPDIR:-/tmp}/build.${pkgname}"

rm -rf "${builddir}"

meson setup "${builddir}" "${srcdir}" \
  --prefix="${pkgdir}" \
  -Dwrap_mode=nodownload \
  -Dbuildtype=release \
  -Db_lto=true \
  -Db_lto_mode=thin \
  -Dcoretext=enabled \
  -Dfreetype=enabled \
  -Dglib=disabled \
  -Dgobject=disabled \
  -Dcairo=disabled \
  -Dchafa=disabled \
  -Dicu=disabled \
  -Dtests=disabled \
  -Dintrospection=disabled \
  -Ddocs=disabled \
  -Dutilities=disabled \
  "$@"

meson compile -C "${builddir}"

rm -rf "${pkgdir}"

meson install -C "${builddir}" --tags runtime,devel
stow -Rd "${STOWDIR}" "${pkgname}"

rm -rf "${builddir}"
