#!/usr/bin/env bash -e
#
# dav1d
# https://code.videolan.org/videolan/dav1d.git
#

set -e

PS4='+ ${BASH_SOURCE}:${LINENO}: '

error_report() {
    echo "Error on line $1"
}

trap 'error_report $LINENO' ERR

cd "$(dirname "$0")"
set -a; source build.env; set +a

pkgname="dav1d"
pkgdir="$1"
srcdir="src/dav1d"
builddir="${TMPDIR:-/tmp}/build.${pkgname}"

rm -rf "${builddir}"

meson setup "${builddir}" "${srcdir}" \
  --prefix="${pkgdir}" \
  -Dwrap_mode=nodownload \
  -Dbuildtype=release \
  -Db_lto=true \
  -Db_lto_mode=thin \
  -Denable_tools=false \
  -Denable_tests=false \
  # "$@"

meson compile -C "${builddir}"

# rm -rf "${pkgdir}"

meson install -C "${builddir}"

rm -rf "${builddir}"

# vi:set ts=2 sw=2 et:
