#!/bin/bash -e
#
# libpng
# https://github.com/pnggroup/libpng.git
#
cd "$(dirname "$0")"
set -a; . .env; set +a

pkgname="libpng"
pkgdir="${STOWDIR}/${pkgname}"
srcdir="src/libpng"
builddir="${TMPDIR:-/tmp}/build.${pkgname}"

echo
echo "*** $0: started"

rm -rf "${builddir}"

cmake -B "${builddir}" -S "${srcdir}" \
  -DCMAKE_INSTALL_PREFIX="${pkgdir}" \
  -DCMAKE_INSTALL_NAME_DIR="${pkgdir}/lib" \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON \
  -DSKIP_INSTALL_EXPORT=ON \
  -DPNG_STATIC=OFF \
  -DPNG_FRAMEWORK=OFF \
  -DPNG_TESTS=OFF \
  -DPNG_TOOLS=OFF \
  "$@"

cmake --build "${builddir}"

rm -rf "${pkgdir}"

cmake --install "${builddir}"
rm -rf "${pkgdir}"/{bin,lib/cmake,share}
stow -Rd "${STOWDIR}" "${pkgname}"

rm -rf "${builddir}"

echo "*** $0: finished"
