#!/usr/bin/env bash -e

cd "$(dirname "$0")"

./build-vulkan
./build-moltenvk
./build-shaderc
./build-lcms2
./build-libplacebo
./build-dav1d
./build-svt-av1
./build-x264
./build-x265
./build-libvpx
./build-opus
./build-libwebp
./build-libpng
./build-brotli
./build-highway
./build-libjxl
./build-freetype
./build-harfbuzz
./build-freetype
./build-fribidi
./build-libunibreak
./build-libass
./build-libbluray
./build-libdvdread
./build-libdvdnav
./build-ffmpeg
./build-luajit
./build-libarchive
./build-uchardet
./build-mpv "$@"
