#!/usr/bin/env bash -e
#
# MoltenVK
# https://github.com/KhronosGroup/MoltenVK.git
#
cd "$(dirname "$0")"
set -a; . .env; set +a

pkgname="moltenvk"
pkgdir="${STOWDIR}/${pkgname}"
srcdir="src/MoltenVK"
builddir="Package/Latest/MoltenVK/dynamic/dylib/macOS"
xcodebuild="xcodebuild ARCHS=$(uname -m) ONLY_ACTIVE_ARCH=YES"

cd "${srcdir}"

sed -i '' 's/xcodebuild "$@"/'"${xcodebuild}"' "$@"/g' fetchDependencies
sed -i '' 's/XCODEBUILD := .*/XCODEBUILD := '"${xcodebuild}"'/' Makefile
./fetchDependencies --macos --v-headers-root "${PREFIX}"
make macos MVK_CONFIG_LOG_LEVEL=1 "$@"

sed -i '' 's#\./#../../../lib/#' "${builddir}"/MoltenVK_icd.json
cat "${builddir}"/MoltenVK_icd.json

rm -rf "${pkgdir}"

install -d "${pkgdir}"/{lib,etc/vulkan/icd.d}
install -vm755 "${builddir}"/libMoltenVK.dylib "${pkgdir}"/lib
install -vm644 "${builddir}"/MoltenVK_icd.json "${pkgdir}"/etc/vulkan/icd.d
stow -Rd "${STOWDIR}" "${pkgname}"
