#!/usr/bin/env -S bash -e
#
# uchardet
# https://gitlab.freedesktop.org/uchardet/uchardet.git
#
cd "$(dirname "$0")"
set -a; . .env; set +a

pkgname="uchardet"
pkgdir="${STOWDIR}/${pkgname}"
srcdir="src/uchardet"
builddir="${TMPDIR:-/tmp}/build.${pkgname}"

echo
echo "*** $0: started"

rm -rf "${builddir}"

cmake -B "${builddir}" -S "${srcdir}" \
  -DCMAKE_INSTALL_PREFIX="${pkgdir}" \
  -DCMAKE_INSTALL_NAME_DIR="${pkgdir}/lib" \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON \
  -DBUILD_BINARY=OFF \
  -DBUILD_STATIC=OFF \
  -Wno-dev \
  "$@"

cmake --build "${builddir}"

rm -rf "${pkgdir}"

cmake --install "${builddir}"
rm -rf "${pkgdir}"/{lib/cmake,share}
stow -Rd "${STOWDIR}" "${pkgname}"

rm -rf "${builddir}"

echo "*** $0: finished"
