#!/usr/bin/env bash -e
#
# FFmpeg
# https://git.ffmpeg.org/ffmpeg.git
#
cd "$(dirname "$0")"
set -a; source build.env; set +a

pkgname="ffmpeg"
pkgdir="${STOWDIR}/${pkgname}"
srcdir="src/ffmpeg"

cd "${srcdir}"

./configure \
  --prefix="${pkgdir}" \
  --pkg-config="${PKG_CONFIG}" \
  --arch="$(uname -m)" \
  --cpu=host \
  --cc=clang \
  --enable-shared \
  --enable-lto=thin \
  --enable-gpl \
  --enable-version3 \
  --enable-nonfree \
  --enable-lcms2 \
  --enable-libass \
  --enable-libdav1d \
  --enable-libfreetype \
  --enable-libfribidi \
  --enable-libharfbuzz \
  --enable-libjxl \
  --enable-libopus \
  --enable-libplacebo \
  --enable-libshaderc \
  --enable-libsvtav1 \
  --enable-libvpx \
  --enable-libwebp \
  --enable-libx264 \
  --enable-libx265 \
  --enable-libxml2 \
  --enable-openssl \
  --disable-static \
  --disable-debug \
  --disable-doc \
  --disable-sdl2 \
  --disable-libxcb \
  --disable-xlib \
  --disable-hwaccels \
  --enable-hwaccel=h264_videotoolbox \
  --enable-hwaccel=hevc_videotoolbox \
  --enable-hwaccel=mpeg4_videotoolbox \
  --enable-hwaccel=prores_videotoolbox \
  --enable-hwaccel=vp9_videotoolbox \
  "$@"

make -j4

rm -rf "${pkgdir}"

make install
rm -rf "${pkgdir}"/share
stow -Rd "${STOWDIR}" "${pkgname}"

# vi:set ts=2 sw=2 et:
