#!/usr/bin/env bash -e
#
# libunibreak
# https://github.com/adah1972/libunibreak.git
#
cd "$(dirname "$0")"
set -a; . .env; set +a

pkgname="libunibreak"
pkgdir="${STOWDIR}/${pkgname}"
srcdir="src/libunibreak"

cd "${srcdir}"

./configure \
  --prefix="${pkgdir}" \
  --enable-shared \
  --disable-static \
  "$@"

make -j4

rm -rf "${pkgdir}"

make install
rm -f "${pkgdir}"/lib/*.la
stow -Rd "${STOWDIR}" "${pkgname}"
