#!/usr/bin/env bash -e
#
# Little-CMS
# https://github.com/mm2/Little-CMS.git
#
cd "$(dirname "$0")"
set -a; . .env; set +a

pkgname="lcms2"
pkgdir="${STOWDIR}/${pkgname}"
srcdir="src/Little-CMS"
builddir="${TMPDIR:-/tmp}/build.${pkgname}"

rm -rf "${builddir}"

meson setup "${builddir}" "${srcdir}" \
  --prefix="${pkgdir}" \
  -Dwrap_mode=nodownload \
  -Dbuildtype=release \
  -Db_lto=true \
  -Db_lto_mode=thin \
  -Djpeg=disabled \
  -Dtiff=disabled \
  "$@"

meson compile -C "${builddir}"

rm -rf "${pkgdir}"

meson install -C "${builddir}"
stow -Rd "${STOWDIR}" "${pkgname}"

rm -rf "${builddir}"
