#!/usr/bin/env bash -e
#
# Vulkan Headers
# https://github.com/KhronosGroup/Vulkan-Headers.git
#
# Vulkan Loader
# https://github.com/KhronosGroup/Vulkan-Loader.git
#

set -e

PS4='+ ${BASH_SOURCE}:${LINENO}: '

error_report() {
    echo "Error on line $1"
}

trap 'error_report $LINENO' ERR

cd "$(dirname "$0")"
set -a; source build.env; set +a

pkgname="vulkan"
pkgdir="$1"
headerssrcdir="src/Vulkan-Headers"
loadersrcdir="src/Vulkan-Loader"
builddir="${TMPDIR:-/tmp}/build.${pkgname}"

icddatadirs=(
  "$1/share"
  "/usr/local/share"
)

rm -rf "${builddir}" # "${pkgdir}"

cmake \
  -B "${builddir}" \
  -S "${headerssrcdir}" \
  -DCMAKE_INSTALL_PREFIX="${pkgdir}" \
  -DCMAKE_BUILD_TYPE=Release

cmake --install "${builddir}"

rm -rf "${builddir}"

cmake \
  -B "${builddir}" \
  -S "${loadersrcdir}" \
  -DCMAKE_INSTALL_PREFIX="${pkgdir}" \
  -DCMAKE_INSTALL_LIBDIR=lib \
  -DCMAKE_INSTALL_NAME_DIR="${pkgdir}/lib" \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON \
  -DVULKAN_HEADERS_INSTALL_DIR="${pkgdir}" \
  -DFALLBACK_DATA_DIRS="$( IFS=:; echo "${icddatadirs[*]}" )" \
  # "$@"

cmake --build "${builddir}"
cmake --install "${builddir}"

rm -rf "${builddir}"

# vi:set ts=2 sw=2 et:
