#!/usr/bin/env -S bash -e
#
# Opus
# https://gitlab.xiph.org/xiph/opus.git
#
cd "$(dirname "$0")"
set -a; . .env; set +a

pkgname="opus"
pkgdir="${STOWDIR}/${pkgname}"
srcdir="src/opus"
builddir="${TMPDIR:-/tmp}/build.${pkgname}"

echo
echo "*** $0: started"

rm -rf "${builddir}"

meson setup "${builddir}" "${srcdir}" \
  --prefix="${pkgdir}" \
  -Dwrap_mode=nodownload \
  -Dbuildtype=release \
  -Db_lto=true \
  -Db_lto_mode=thin \
  -Ddeep-plc=enabled \
  -Ddred=enabled \
  -Dosce=enabled \
  -Dextra-programs=disabled \
  -Dtests=disabled \
  -Ddocs=disabled \
  "$@"

meson compile -C "${builddir}"

rm -rf "${pkgdir}"

meson install -C "${builddir}"
stow -Rd "${STOWDIR}" "${pkgname}"

rm -rf "${builddir}"

echo "*** $0: finished"
