#!/bin/bash -e
#
# libbluray
# https://code.videolan.org/videolan/libbluray.git
#
cd "$(dirname "$0")"
set -a; . .env; set +a

pkgname="libbluray"
pkgdir="${STOWDIR}/${pkgname}"
srcdir="src/libbluray"
builddir="${TMPDIR:-/tmp}/build.${pkgname}"

echo
echo "*** $0: started"

rm -rf "${builddir}"

meson setup "${builddir}" "${srcdir}" \
  --prefix="${pkgdir}" \
  -Ddefault_library=shared \
  -Dwrap_mode=nodownload \
  -Dbuildtype=release \
  -Db_lto=true \
  -Db_lto_mode=thin \
  -Dfreetype=enabled \
  -Dlibxml2=enabled \
  -Denable_tools=false \
  -Dbdj_jar=disabled \
  -Dfontconfig=disabled \
  "$@"

meson compile -C "${builddir}"

rm -rf "${pkgdir}"

meson install -C "${builddir}"
stow -Rd "${STOWDIR}" "${pkgname}"

rm -rf "${builddir}"

echo "*** $0: finished"
