#!/usr/bin/env zsh -e
#
# FreeType
# https://gitlab.freedesktop.org/freetype/freetype.git
#

set -e

PS4='+ ${BASH_SOURCE}:${LINENO}: '

error_report() {
    echo "Error on line $1"
}

trap 'error_report $LINENO' ERR

cd "$(dirname "$0")"
set -a; source build.env; set +a
source utils/pkg-import

pkgname="freetype"
pkgdir=$(echo "$1" | awk -F= '{print $2}')
srcdir="src/freetype"
builddir="${TMPDIR:-/tmp}/build.${pkgname}"

import_local_pkg $pkgdir

rm -rf "${builddir}"

meson setup "${builddir}" "${srcdir}" \
  --prefix="${pkgdir}" \
  -Dwrap_mode=nodownload \
  -Dbuildtype=release \
  -Db_lto=true \
  -Db_lto_mode=thin \
  -Dbrotli=enabled \
  -Dbzip2=enabled \
  -Dharfbuzz=enabled \
  -Dmmap=enabled \
  -Dpng=enabled \
  -Dzlib=system \
  "$@"

meson compile -C "${builddir}"

# rm -rf "${pkgdir}"

meson install -C "${builddir}"

rm -rf "${builddir}"

# vi:set ts=2 sw=2 et:
