#!/usr/bin/env -S bash -e
#
# shaderc
# https://github.com/google/shaderc.git
#
cd "$(dirname "$0")"
set -a; . .env; set +a

pkgname="shaderc"
pkgdir="${STOWDIR}/${pkgname}"
srcdir="src/shaderc"
builddir="${TMPDIR:-/tmp}/build.${pkgname}"

echo
echo "*** $0: started"

rm -rf "${builddir}"

cd "${srcdir}"
sed -i '' 's/${SHADERC_SKIP_INSTALL}/ON/g' third_party/CMakeLists.txt
sed -i '' '/^.*GLSLANG_ENABLE_INSTALL.*$/d' third_party/CMakeLists.txt
./utils/git-sync-deps
cd -

cmake -B "${builddir}" -S "${srcdir}" \
  -DCMAKE_INSTALL_PREFIX="${pkgdir}" \
  -DCMAKE_INSTALL_NAME_DIR="${pkgdir}/lib" \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON \
  -DSHADERC_SKIP_TESTS=ON \
  -DSHADERC_SKIP_EXAMPLES=ON \
  "$@"

cmake --build "${builddir}"

rm -rf "${pkgdir}"

cmake --install "${builddir}"
rm -rf "${pkgdir}"/{bin,lib/{*.a,pkgconfig/*{combined,static}.pc}}
stow -Rd "${STOWDIR}" "${pkgname}"

rm -rf "${builddir}"

echo "*** $0: finished"
