#!/usr/bin/env bash -e
#
# Vulkan Headers
# https://github.com/KhronosGroup/Vulkan-Headers.git
#
# Vulkan Loader
# https://github.com/KhronosGroup/Vulkan-Loader.git
#
cd "$(dirname "$0")"
set -a; source build.env; set +a

pkgname="vulkan"
pkgdir="${PKGPREFIX:-/opt/local}/${pkgname}"
headerssrcdir="src/Vulkan-Headers"
loadersrcdir="src/Vulkan-Loader"
builddir="${TMPDIR:-/tmp}/build.${pkgname}"

icddatadirs=(
  "${PKGPREFIX:-/opt/local}/moltenvk/share"
  "/usr/local/share"
)

rm -rf "${builddir}" "${pkgdir}"

cmake \
  -B "${builddir}" \
  -S "${headerssrcdir}" \
  -DCMAKE_INSTALL_PREFIX="${pkgdir}" \
  -DCMAKE_BUILD_TYPE=Release

cmake --install "${builddir}"

rm -rf "${builddir}"

cmake \
  -B "${builddir}" \
  -S "${loadersrcdir}" \
  -DCMAKE_INSTALL_PREFIX="${pkgdir}" \
  -DCMAKE_INSTALL_LIBDIR=lib \
  -DCMAKE_INSTALL_NAME_DIR="${pkgdir}/lib" \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON \
  -DVULKAN_HEADERS_INSTALL_DIR="${pkgdir}" \
  -DFALLBACK_DATA_DIRS="$( IFS=:; echo "${icddatadirs[*]}" )" \
  "$@"

cmake --build "${builddir}"
cmake --install "${builddir}"

rm -rf "${builddir}"

# vi:set ts=2 sw=2 et:
