#!/usr/bin/env bash -e
#
# libplacebo
# https://code.videolan.org/videolan/libplacebo.git
#

set -e

PS4='+ ${BASH_SOURCE}:${LINENO}: '

error_report() {
    echo "Error on line $1"
}

trap 'error_report $LINENO' ERR

cd "$(dirname "$0")"
set -a; source build.env; set +a
source utils/pkg-import

pkgname="libplacebo"
pkgdir="$1"
srcdir="src/libplacebo"
builddir="${TMPDIR:-/tmp}/build.$pkgname"

import_local_pkg $pkgdir
echo $PKG_CONFIG_PATH
echo $CPPFLAGS
echo $LDFLAGS
# import_homebrew_pkg glslang
# import_homebrew_pkg spirv-tools

rm -rf "${builddir}"

meson setup "$builddir" "$srcdir" \
  --prefix="$pkgdir" \
  -Dwrap_mode=nodownload \
  -Dbuildtype=release \
  -Db_lto=true \
  -Db_lto_mode=thin \
  -Dvulkan-registry="$pkgdir/share/vulkan/registry/vk.xml" \
  -Dvulkan=enabled \
  -Dshaderc=enabled \
  -Dlcms=enabled \
  -Dxxhash=enabled \
  -Dopengl=enabled \
  -Dglslang=disabled \
  -Dd3d11=disabled \
  -Ddemos=false \
  # "$@"

meson compile -C "$builddir"

# rm -rf "${pkgdir}"

meson install -C "$builddir"

rm -rf "$builddir"

# vi:set ts=2 sw=2 et:
