#!/usr/bin/env bash -e
#
# HarfBuzz
# https://github.com/harfbuzz/harfbuzz.git
#

set -e

PS4='+ ${BASH_SOURCE}:${LINENO}: '

error_report() {
    echo "Error on line $1"
}

trap 'error_report $LINENO' ERR

cd "$(dirname "$0")"
set -a; source build.env; set +a
source utils/pkg-import

pkgname="harfbuzz"
pkgdir="$1"
srcdir="src/harfbuzz"
builddir="${TMPDIR:-/tmp}/build.${pkgname}"

import_local_pkg $pkgdir

rm -rf "${builddir}"

meson setup "${builddir}" "${srcdir}" \
  --prefix="${pkgdir}" \
  -Dwrap_mode=nodownload \
  -Dbuildtype=release \
  -Db_lto=true \
  -Db_lto_mode=thin \
  -Dcoretext=enabled \
  -Dfreetype=enabled \
  -Dglib=auto \
  -Dgobject=disabled \
  -Dcairo=disabled \
  -Dchafa=disabled \
  -Dicu=disabled \
  -Dtests=disabled \
  -Dintrospection=disabled \
  -Ddocs=disabled \
  -Dutilities=disabled \
  # "$@"

meson compile -C "${builddir}"

# rm -rf "${pkgdir}"

meson install -C "${builddir}"

rm -rf "${builddir}"

# vi:set ts=2 sw=2 et:
