#!/usr/bin/env -S bash -e
#
# FreeType
# https://gitlab.freedesktop.org/freetype/freetype.git
#
cd "$(dirname "$0")"
set -a; . .env; set +a

pkgname="freetype"
pkgdir="${STOWDIR}/${pkgname}"
srcdir="src/freetype"
builddir="${TMPDIR:-/tmp}/build.${pkgname}"

echo
echo "*** $0: started"

rm -rf "${builddir}"

meson setup "${builddir}" "${srcdir}" \
  --prefix="${pkgdir}" \
  -Dwrap_mode=nodownload \
  -Dbuildtype=release \
  -Db_lto=true \
  -Db_lto_mode=thin \
  -Dbrotli=enabled \
  -Dbzip2=enabled \
  -Dmmap=enabled \
  -Dpng=enabled \
  -Dzlib=system \
  "$@"

meson compile -C "${builddir}"

rm -rf "${pkgdir}"

meson install -C "${builddir}" --tags runtime,devel
stow -Rd "${STOWDIR}" "${pkgname}"

rm -rf "${builddir}"

echo "*** $0: finished"
