#!/bin/bash -e
#
# MoltenVK
# https://github.com/KhronosGroup/MoltenVK.git
#
cd "$(dirname "$0")"
set -a; . .env; set +a

pkgname="moltenvk"
pkgdir="${STOWDIR}/${pkgname}"
srcdir="src/MoltenVK"
builddir="${TMPDIR:-/tmp}/build.${pkgname}"

echo
echo "*** $0: started"

rm -rf "${builddir}"

cmake -B "${builddir}" -S "${srcdir}" \
  -DCMAKE_INSTALL_PREFIX="${pkgdir}" \
  -DCMAKE_INSTALL_NAME_DIR="${pkgdir}/lib" \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON \
  -DMVK_CONFIG_LOG_LEVEL=error \
  -DMVK_USE_METAL_PRIVATE_API=ON \
  -DCPM_SOURCE_CACHE=src/CPM \
  -Wno-dev \
  "$@"

cmake --build "${builddir}"

rm -rf "${pkgdir}"

cmake --install "${builddir}"
stow -Rd "${STOWDIR}" "${pkgname}"

rm -rf "${builddir}"

echo "*** $0: finished"
