#!/usr/bin/env -S bash -e
#
# GNU FriBidi
# https://github.com/fribidi/fribidi.git
#
cd "$(dirname "$0")"
set -a; . .env; set +a

pkgname="fribidi"
pkgdir="${STOWDIR}/${pkgname}"
srcdir="src/fribidi"
builddir="${TMPDIR:-/tmp}/build.${pkgname}"

echo
echo "*** $0: started"

rm -rf "${builddir}"

meson setup "${builddir}" "${srcdir}" \
  --prefix="${pkgdir}" \
  -Dwrap_mode=nodownload \
  -Dbuildtype=release \
  -Db_lto=true \
  -Db_lto_mode=thin \
  -Dbin=false \
  -Ddeprecated=false \
  -Ddocs=false \
  -Dtests=false \
  "$@"

meson compile -C "${builddir}"

rm -rf "${pkgdir}"

meson install -C "${builddir}"
stow -Rd "${STOWDIR}" "${pkgname}"

rm -rf "${builddir}"

echo "*** $0: finished"
