#!/usr/bin/env bash -e
#
# libplacebo
# https://code.videolan.org/videolan/libplacebo.git
#
cd "$(dirname "$0")"
set -a; . .env; set +a

pkgname="libplacebo"
pkgdir="${STOWDIR}/${pkgname}"
srcdir="src/libplacebo"
builddir="${TMPDIR:-/tmp}/build.${pkgname}"

rm -rf "${builddir}"

meson setup "${builddir}" "${srcdir}" \
  --prefix="${pkgdir}" \
  -Dwrap_mode=nodownload \
  -Dbuildtype=release \
  -Db_lto=true \
  -Db_lto_mode=thin \
  -Dvulkan-registry="${PREFIX}/share/vulkan/registry/vk.xml" \
  -Dvulkan=enabled \
  -Dshaderc=enabled \
  -Dlcms=enabled \
  -Dxxhash=enabled \
  -Dopengl=disabled \
  -Dd3d11=disabled \
  -Dglslang=disabled \
  -Ddemos=false \
  "$@"

meson compile -C "${builddir}"

rm -rf "${pkgdir}"

meson install -C "${builddir}"
stow -Rd "${STOWDIR}" "${pkgname}"

rm -rf "${builddir}"
