#!/usr/bin/env bash -e
#
# x264
# https://code.videolan.org/videolan/x264.git
#
cd "$(dirname "$0")"
set -a; . .env; set +a

pkgname="x264"
pkgdir="${STOWDIR}/${pkgname}"
srcdir="src/x264"

cd "${srcdir}"

./configure \
  --prefix="${pkgdir}" \
  --enable-shared \
  --enable-lto \
  --disable-cli \
  --disable-opencl \
  "$@"

make -j4

rm -rf "${pkgdir}"

make install
stow -Rd "${STOWDIR}" "${pkgname}"
