#!/bin/bash -e
#
# libdvdnav
# https://code.videolan.org/videolan/libdvdnav.git
#
cd "$(dirname "$0")"
set -a; . .env; set +a

pkgname="libdvdnav"
pkgdir="${STOWDIR}/${pkgname}"
srcdir="src/libdvdnav"

echo
echo "*** $0: started"

cd "${srcdir}"

./configure \
  --prefix="${pkgdir}" \
  --enable-shared \
  --disable-static \
  --disable-apidoc \
  "$@"

make -j4

rm -rf "${pkgdir}"

make install
rm -rf "${pkgdir}"/lib/*.la "${pkgdir}"/share
stow -Rd "${STOWDIR}" "${pkgname}"

echo "*** $0: finished"
