#!/usr/bin/env bash -e
#
# FreeType
# https://gitlab.freedesktop.org/freetype/freetype.git
#
cd "$(dirname "$0")"
set -a; source build.env; set +a
source utils/pkg-import

pkgname="freetype"
pkgdir="${PKGPREFIX:-/opt/local}/${pkgname}"
srcdir="src/freetype"
builddir="${TMPDIR:-/tmp}/build.${pkgname}"

import_local_pkg freetype
import_local_pkg harfbuzz

rm -rf "${builddir}"

meson setup "${builddir}" "${srcdir}" \
  --prefix="${pkgdir}" \
  -Dwrap_mode=nodownload \
  -Dbuildtype=release \
  -Db_lto=true \
  -Db_lto_mode=thin \
  -Dbrotli=enabled \
  -Dbzip2=enabled \
  -Dharfbuzz=enabled \
  -Dmmap=enabled \
  -Dpng=enabled \
  -Dzlib=system \
  "$@"

meson compile -C "${builddir}"

rm -rf "${pkgdir}"

meson install -C "${builddir}"

rm -rf "${builddir}"

# vi:set ts=2 sw=2 et:
