#!/bin/bash -e
#
# libdvdnav
# https://code.videolan.org/videolan/libdvdnav.git
#
cd "$(dirname "$0")"
set -a; . .env; set +a

pkgname="libdvdnav"
pkgdir="${STOWDIR}/${pkgname}"
srcdir="src/libdvdnav"
builddir="${TMPDIR:-/tmp}/build.${pkgname}"

echo
echo "*** $0: started"

rm -rf "${builddir}"

meson setup "${builddir}" "${srcdir}" \
  --prefix="${pkgdir}" \
  -Ddefault_library=shared \
  -Dwrap_mode=nodownload \
  -Dbuildtype=release \
  -Db_lto=true \
  -Db_lto_mode=thin \
  -Denable_docs=false \
  -Denable_examples=false \
  "$@"

meson compile -C "${builddir}"

rm -rf "${pkgdir}"

meson install -C "${builddir}" --tags runtime,devel
stow -Rd "${STOWDIR}" "${pkgname}"

rm -rf "${builddir}"

echo "*** $0: finished"
