#!/usr/bin/env -S bash -e
#
# dav1d
# https://code.videolan.org/videolan/dav1d.git
#
cd "$(dirname "$0")"
set -a; . .env; set +a

pkgname="dav1d"
pkgdir="${STOWDIR}/${pkgname}"
srcdir="src/dav1d"
builddir="${TMPDIR:-/tmp}/build.${pkgname}"

echo
echo "*** $0: started"

rm -rf "${builddir}"

meson setup "${builddir}" "${srcdir}" \
  --prefix="${pkgdir}" \
  -Dwrap_mode=nodownload \
  -Dbuildtype=release \
  -Db_lto=true \
  -Db_lto_mode=thin \
  -Denable_tools=false \
  -Denable_tests=false \
  "$@"

meson compile -C "${builddir}"

rm -rf "${pkgdir}"

meson install -C "${builddir}"
stow -Rd "${STOWDIR}" "${pkgname}"

rm -rf "${builddir}"

echo "*** $0: finished"
