#!/usr/bin/env bash -e
#
# HarfBuzz
# https://github.com/harfbuzz/harfbuzz.git
#
cd "$(dirname "$0")"
set -a; source build.env; set +a
source utils/pkg-import

pkgname="harfbuzz"
pkgdir="/opt/local/${pkgname}"
srcdir="src/harfbuzz"
builddir="${TMPDIR:-/tmp}/build.${pkgname}"

import_local_pkg freetype
import_local_pkg harfbuzz

rm -rf "${builddir}"

meson setup "${builddir}" "${srcdir}" \
  --prefix="${pkgdir}" \
  -Dwrap_mode=nodownload \
  -Dbuildtype=release \
  -Db_lto=true \
  -Db_lto_mode=thin \
  -Dcoretext=enabled \
  -Dfreetype=enabled \
  -Dglib=auto \
  -Dgobject=disabled \
  -Dcairo=disabled \
  -Dchafa=disabled \
  -Dicu=disabled \
  -Dtests=disabled \
  -Dintrospection=disabled \
  -Ddocs=disabled \
  -Dutilities=disabled \
  "$@"

meson compile -C "${builddir}"

rm -rf "${pkgdir}"

meson install -C "${builddir}"

rm -rf "${builddir}"

# vi:set ts=2 sw=2 et:
