#!/usr/bin/env bash -e
#
# libass
# https://github.com/libass/libass.git
#
cd "$(dirname "$0")"
set -a; source build.env; set +a

pkgname="libass"
pkgdir="${STOWDIR}/${pkgname}"
srcdir="src/libass"
builddir="${TMPDIR:-/tmp}/build.${pkgname}"

rm -rf "${builddir}"

meson setup "${builddir}" "${srcdir}" \
  --prefix="${pkgdir}" \
  -Ddefault_library=shared \
  -Dwrap_mode=nodownload \
  -Dbuildtype=release \
  -Db_lto=true \
  -Db_lto_mode=thin \
  -Dcoretext=enabled \
  -Dasm=enabled \
  -Dlibunibreak=enabled \
  -Dtest=disabled \
  -Dcompare=disabled \
  -Dprofile=disabled \
  -Dfuzz=disabled \
  -Dcheckasm=disabled \
  -Dfontconfig=disabled \
  -Ddirectwrite=disabled \
  "$@"

meson compile -C "${builddir}"

rm -rf "${pkgdir}"

meson install -C "${builddir}"
stow -Rd "${STOWDIR}" "${pkgname}"

rm -rf "${builddir}"
