#!/hint/bash

import_local_pkg() {
  local prefix="$1"
  local pcdir="$prefix/lib/pkgconfig"
  local pcpath="${PKG_CONFIG_PATH:+${PKG_CONFIG_PATH}:}"

  # if [ $# != 1 ] || [ -z "${pkgname}" ]; then
  #   echo -e "\033[1;31mERROR\033[0m ${FUNCNAME}: invalid argument."
  #   exit 1
  # fi

  if [ ! -d "${pcdir}" ]; then
    echo -e "\033[1;33mWARNING\033[0m ${FUNCNAME}: ${pcdir} does not exist."
  fi

  export PKG_CONFIG_PATH="${pcpath}${pcdir}"
}

import_homebrew_pkg() {
  local pkgprefix="$(brew --prefix --installed "$1")"
  local pcdir="${pkgprefix}/lib/pkgconfig"
  local pcpath="${PKG_CONFIG_PATH:+${PKG_CONFIG_PATH}:}"

  if [ -z "${pkgprefix}" ]; then
    exit 1
  fi

  if [ ! -d "${pcdir}" ]; then
    echo -e "\033[1;33mWARNING\033[0m ${FUNCNAME}: ${pcdir} does not exist."
  fi

  export PKG_CONFIG_PATH="${pcpath}${pcdir}"
}

# vi:set ts=2 sw=2 et:
