---
name: Build & Upload Artifact

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/build.yml"
      - "build-*"
      - "fetch"

jobs:
  build:
    runs-on: macos-15

    permissions:
      contents: read
      id-token: write
      attestations: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Select Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode_26.0.app
          xcodebuild -version

      - name: Create Stow Directory
        run: |
          sudo mkdir -p /opt/local
          sudo chown "$USER":admin /opt/local
          mkdir -p /opt/local/stow

      - name: Install Dependencies
        run: |
          brew update -q
          brew uninstall -q cmake
          xargs brew install -q --formula < homebrew/build-deps.txt

      - name: Fetch Sources
        run: ./fetch all

      - name: Build & Install
        run: ./build-all --bundle
        env:
          MACOSX_DEPLOYMENT_TARGET: 15.5

      - name: Upload Artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: mpv-macos-15-arm64
          path: mpv.tar.gz
          if-no-files-found: error
          compression-level: 0
          overwrite: true

      - name: Attest Artifact
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: mpv-macos-15-arm64.zip
          subject-digest: sha256:${{ steps.upload.outputs.artifact-digest }}
