name: Build & Upload Artifact

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/build.yml'
      - 'build-*'
      - 'fetch'

jobs:
  build:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode_16.3.app
          xcodebuild -version

      - name: Create Stow Directory
        run: |
          sudo mkdir -p /opt/local
          sudo chown "$USER":admin /opt/local
          mkdir -p /opt/local/stow

      - name: Install Dependencies
        run: |
          brew update -q
          xargs brew install -q --formula < homebrew/build-deps.txt

      - name: Fetch Sources
        run: ./fetch all

      - name: Build & Install
        run: ./build-all --bundle
        env:
          MACOSX_DEPLOYMENT_TARGET: 15.4

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mpv-macos-15-arm64
          path: mpv.tar.gz
          compression-level: 0
          overwrite: true
