---
name: Lint

on:
  push:
  pull_request:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Check
        run: shellcheck .env build-* fetch

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Check
        run: yamllint --strict .

  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install
        uses: editorconfig-checker/action-editorconfig-checker@main

      - name: Check
        run: editorconfig-checker

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Check
        uses: raven-actions/actionlint@v2

  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v6

      - name: Install
        run: npm install prettier@next

      - name: Check
        run: npx prettier --check .
